#!/usr/bin/env bash
set -eo pipefail

# Create Tor onion-service dir for storing hostname, hs_ed25519_secret_key, and hs_ed25519_public_key files
echo "[TOR] Ensuring onion-service directory exists"
mkdir -p "${HOME}/onion-service"

################################################################################
# APPLY PERSISTENT ADDRESS/KEYS/TORRC IF SET
################################################################################

# Write the hs_ed25519_secret_key file from config folder if set
if [ -f "${HOME}/config/hs_ed25519_secret_key.erb" ]; then
    echo "[TOR] Compiling user-defined hs_ed25519_secret_key from config/hs_ed25519_secret_key.erb"
    erb "${HOME}/config/hs_ed25519_secret_key.erb" > "${HOME}/onion-service/hs_ed25519_secret_key"
else
    echo "[TOR] WARNING: No hs_ed25519_secret_key found in config folder"
fi

# Write the hs_ed25519_public_key file from config folder if set
if [ -f "${HOME}/config/hs_ed25519_public_key.erb" ]; then
    echo "[TOR] Compiling user-defined hs_ed25519_public_key from config/hs_ed25519_public_key.erb"
    erb "${HOME}/config/hs_ed25519_public_key.erb" > "${HOME}/onion-service/hs_ed25519_public_key"
else
    echo "[TOR] WARNING: No hs_ed25519_public_key found in config folder"
fi

# Write the hostname file using ONION_LOCATION if set
echo "[TOR] Writing onion-service/hostname file from ONION_LOCATION env"
if [ ! -z "${ONION_LOCATION}" ]; then
    echo "${ONION_LOCATION}" > "${HOME}/onion-service/hostname"
else
    echo "[TOR] WARNING: env ONION_LOCATION is not set"
fi

# Generate the torrc file using the app's custom template (if set), else the default template
if [ -f "${HOME}/config/torrc.erb" ]; then
    echo "[TOR] Compiling user-defined torrc from config/torrc.erb"
    erb "${HOME}/config/torrc.erb" > "${HOME}/tor/etc/tor/torrc"
else
    echo "[TOR] Using default torrc.erb"
    erb "${HOME}/tor/torrc.erb" > "${HOME}/tor/etc/tor/torrc"
fi

################################################################################
# GENERATE ADDRESS/KEYS IF NOT SET
################################################################################

# Generate a new hs_ed25519_secret_key, hs_ed5519_public_key, and hostname if both were not specified
if [ ! -f "${HOME}/onion-service/hs_ed25519_secret_key" ] || [ ! -f "${HOME}/onion-service/hs_ed25519_public_key" ] || [ ! -f "${HOME}/onion-service/hostname" ]; then
    echo "[TOR] WARNING: hs_ed25519_secret_key, hs_ed25519_public_key, and/or hostname were not specified"
    echo "[TOR] WARNING: Attempting to generate a new hs_ed25519_secret_key, hs_ed25519_public_key, and hostname"

    # Ensure that hs_ed25519_secret_key, hs_ed5519_public_key, and hostname files are really gone
    rm -f "${HOME}/onion-service/hs_ed25519_secret_key" "${HOME}/onion-service/hs_ed5519_public_key" "${HOME}/onion-service/hostname"

    # Start Tor in the background and track the PID
    "${HOME}/tor/bin/tor" -f "${HOME}/tor/etc/tor/torrc" & TOR_PID=$!

    # Wait until hs_ed25519_secret_key, hs_ed5519_public_key, and hostname are generated then kill Tor (for now)
    TOR_AUTOGEN_TRIES_REMAINING=5
    while [ ! -f "${HOME}/onion-service/hs_ed25519_secret_key" ] && [ ! -f "${HOME}/onion-service/hs_ed25519_public_key" ] && [ ! -f "${HOME}/onion-service/hostname" ]; do
        TOR_AUTOGEN_TRIES_REMAINING=$((TOR_AUTOGEN_TRIES_REMAINING-1))
        if [ $TOR_AUTOGEN_TRIES_REMAINING -eq 0 ]; then
            echo "[TOR] FAILURE: Unable to generate a hs_ed25519_secret_key, hs_ed25519_public_key, and hostname"
            exit 1
        fi
        sleep 1
    done
    kill $TOR_PID
    echo "[TOR] Successfully generated new hs_ed25519_secret_key, hs_ed25519_public_key, and hostname"
fi

################################################################################
# VALIDATE, PRINT INFO, START
################################################################################

# Validate Tor config

TOR_HOSTNAME=$(cat "${HOME}/onion-service/hostname")

# Print some useful info
echo ""
echo "[TOR] ==================================================================="
echo "[TOR] Starting onion service at ${TOR_HOSTNAME}"
echo "[TOR] You may dangerously print your hs_ed25519_secret_key by running this command:"
echo "[TOR] heroku ps:exec --dyno=${DYNO} 'cat \"${HOME}/onion-service/hs_ed25519_secret_key\"'"
echo "[TOR] ==================================================================="
echo ""

# Start Tor
"${HOME}/tor/bin/tor" -f "${HOME}/tor/etc/tor/torrc"
